policy:
  - section:
# Enviroment
      - id: ['os']
        block-list: ['Other']
        label:
          - name: 'env: os/windows'
            keys: ['Windows']
          - name: 'env: os/macos'
            keys: ['macOS']
          - name: 'env: os/linux'
            keys: ['Linux']
          - name: 'env: os/ios'
            keys: ['iOS']
          - name: 'env: os/android'
            keys: ['Android']
          - name: 'env: os/ipados'
            keys: ['iPadOS']
          - name: 'env: os/chromeos'
            keys: ['ChromeOS']

      - id: ['browser']
        block-list: ['Other']
        label:
          - name: 'env: browser/chrome'
            keys: ['Chrome']
          - name: 'env: browser/edge'
            keys: ['Microsoft Edge']
          - name: 'env: browser/firefox'
            keys: ['Firefox']
          - name: 'env: browser/safari'
            keys: ['Safari']

      - id: ['device']
        block-list: ['Other']
        label:
          - name: 'env: device/desktop'
            keys: ['Desktop']
          - name: 'env: device/laptop'
            keys: ['Laptop']
          - name: 'env: device/tablet'
            keys: ['Tablet']
          - name: 'env: device/phone'
            keys: ['Phone']

# Primary component (Used in bugs and features)
      - id: ['component']
        block-list: ['Other']
        label:
          - name: 'area: docs'
            keys: ['Docs content']
          - name: 'area: quiz'
            keys: ['Quiz']
          - name: 'area: diagrams'
            keys: ['Diagrams']
          - name: 'area: code-editor'
            keys: ['Code editor / runner']
          - name: 'area: navigation'
            keys: ['Navigation / search']

# Content issues
      - id: ['type-of-issue']
        block-list: []
        label:
          - name: 'content: typo'
            keys: ['Typo/grammar']
          - name: 'content: accuracy'
            keys: ['Factual accuracy']
          - name: 'content: pedagogy'
            keys: ['Pedagogy/sequence (teaches too early/late)']
          - name: 'content: accessibility'
            keys: ['Accessibility (alt text, contrast, keyboard nav)']
          - name: 'content: formatting'
            keys: ['Formatting/layout']
          - name: 'content: broken-link'
            keys: ['Broken link / reference']