site_name: NSW HSC Software Engineering Textbook
site_description: Interactive textbook for NSW HSC Software Engineering 11-12 Syllabus
docs_dir: docs
repo_url: https://github.com/haleema-khatun/Software-Engineering-HSC-Textbook/
site_url: https://haleema-khatun.github.io/Software-Engineering-HSC-Textbook/
repo_name: haleema-khatun/Software-Engineering-HSC-Textbook
edit_uri: edit/main/docs/

copyright: >
  Copyright &copy; 2024 Haleema Khatun –
  <a href="#__consent">Change cookie settings</a>

# Exclude development artifacts from production build
exclude_docs: |
  **/ModulePlan.md
  AI_README.md
  syllabus.md

plugins:
  - search
  - macros:
      module_name: macros/glossary_macros
  - include-markdown
  - git-revision-date-localized
  - kroki:
      EnableMermaid: true
      HttpMethod: POST
      TagFormat: svg
  - awesome-nav:
      filename: ".nav.yml"
  - meta-descriptions:
      export_csv: false
      quiet: false
      enable_checks: false
      min_length: 50
      max_length: 160
      trim: false
      fallback_if_short: false

theme:
  name: material
  language: en
  icon:
    repo: fontawesome/brands/git-alt
  custom_dir: overrides

  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.prune
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.indexes
    - navigation.footer          # ← CRITICAL: ENABLES PREV/NEXT BUTTONS
    - search.highlight
    - search.suggest
    - search.share
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.action.edit
    - content.action.view
    - toc.follow
    - toc.integrate

  font:
    text: Roboto
    code: Roboto Mono

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - extensions.glossary_extension
  - extensions.kroki_wrapper
  - md_in_html
  - smarty
  - tables
  - pymdownx.blocks.details
  - pymdownx.blocks.admonition
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tasklist
  - pymdownx.superfences:
      custom_fences:
        # Python
        - name: python-exec
          class: python-exec
          format: !!python/name:extensions.code_fence_formatter.format_exec
          validator: !!python/name:extensions.code_fence_formatter.fence_validator
        - name: python-template
          class: python-template
          format: !!python/name:extensions.code_fence_formatter.format_template
          validator: !!python/name:extensions.code_fence_formatter.fence_validator
        - name: python-error
          class: python-error
          format: !!python/name:extensions.code_fence_formatter.format_error
          validator: !!python/name:extensions.code_fence_formatter.fence_validator
        # Web Languages
        - name: html-exec
          class: html-exec
          format: !!python/name:extensions.code_fence_formatter.format_exec
          validator: !!python/name:extensions.code_fence_formatter.fence_validator
        - name: html-template
          class: html-template
          format: !!python/name:extensions.code_fence_formatter.format_template
          validator: !!python/name:extensions.code_fence_formatter.fence_validator
        - name: css-exec
          class: css-exec
          format: !!python/name:extensions.code_fence_formatter.format_exec
          validator: !!python/name:extensions.code_fence_formatter.fence_validator
        - name: css-template
          class: css-template
          format: !!python/name:extensions.code_fence_formatter.format_template
          validator: !!python/name:extensions.code_fence_formatter.fence_validator
        - name: javascript-exec
          class: javascript-exec
          format: !!python/name:extensions.code_fence_formatter.format_exec
          validator: !!python/name:extensions.code_fence_formatter.fence_validator
        - name: javascript-template
          class: javascript-template
          format: !!python/name:extensions.code_fence_formatter.format_template
          validator: !!python/name:extensions.code_fence_formatter.fence_validator
        - name: js-exec
          class: js-exec
          format: !!python/name:extensions.code_fence_formatter.format_exec
          validator: !!python/name:extensions.code_fence_formatter.fence_validator
        - name: js-template
          class: js-template
          format: !!python/name:extensions.code_fence_formatter.format_template
          validator: !!python/name:extensions.code_fence_formatter.fence_validator
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.escapeall
  - toc:
      permalink: true
      toc_depth: 3
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: "__span"
      pygments_lang_class: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.blocks.tab:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra_css:
  - assets/diagram-modal.css
  - assets/quiz.css
  - assets/common.css
  - assets/diagram-fix.css
  - assets/cross-reference.css
  - assets/site-banner.css
  - assets/code-runner.css
  - assets/code-editor.css
  - assets/glossary.css
  - stylesheets/extra.css

extra_javascript:
  - assets/diagram-modal.js
  - assets/quiz.js
  - assets/ide-utils.js
  - assets/code-blocks.js
  - assets/glossary.js
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra:
  generator: false
  domain: auto
  # Site-wide alert banner configuration
  site_banner:
    enabled: true
    text: "This textbook is in <strong>beta</strong> – content is actively being refined."
    link_text: "Report issues or suggestions"
    link_url: "/issues/new/choose"
    variant: "warning"
    version: "1"
  # Footer configuration
  footer:
    show_beta_badge: true
  consent:
    title: Cookie consent
    actions:
      - accept
      - manage
    cookies:
      analytics: Google Analytics
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of the textbook. With your consent, you're helping us to
      make software engineering education better for everyone.
  analytics:
    provider: google
    property: G-58275RL1P9
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >- 
            Thanks for your feedback! Help us improve this page by creating an
            <a href="https://github.com/haleema-khatun/Software-Engineering-HSC-Textbook/issues/new/choose" target="_blank" rel="noopener">issue</a>
            on github.
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/haleema-khatun/Software-Engineering-HSC-Textbook

# ============================================
# NAVIGATION STRUCTURE
# Navigation is managed by awesome-nav plugin via .nav.yml
# However, we're adding a manual nav here for prev/next buttons
# The awesome-nav plugin will merge/override as needed
# ============================================

nav:
  - Home: index.md
  
  # ===== YEAR 11 CONTENT =====
  
  - Year 11:
    - year-11/index.md
    
    # Module 1: Programming Fundamentals (18 sections)
    - Programming Fundamentals:
      - year-11/programming-fundamentals/index.md
      - Introduction to Programming: year-11/programming-fundamentals/introduction.md
      - Software Development Life Cycle: year-11/programming-fundamentals/sdlc.md
      - Problem Solving with Algorithms: year-11/programming-fundamentals/algorithms.md
      - Data Types and Structures: year-11/programming-fundamentals/data-types.md
      - Variables and Constants: year-11/programming-fundamentals/variables.md
      - Operators and Expressions: year-11/programming-fundamentals/operators.md
      - Input and Output: year-11/programming-fundamentals/input-output.md
      - Control Structures - Selection: year-11/programming-fundamentals/selection.md
      - Control Structures - Iteration: year-11/programming-fundamentals/iteration.md
      - Functions and Procedures: year-11/programming-fundamentals/functions.md
      - Scope and Lifetime: year-11/programming-fundamentals/scope.md
      - Arrays and Lists: year-11/programming-fundamentals/arrays.md
      - String Manipulation: year-11/programming-fundamentals/strings.md
      - File Handling: year-11/programming-fundamentals/files.md
      - Error Handling: year-11/programming-fundamentals/errors.md
      - Code Documentation: year-11/programming-fundamentals/documentation.md
      - Testing and Debugging: year-11/programming-fundamentals/testing.md
      - Practice Problems: year-11/programming-fundamentals/practice.md
    
    # Module 2: Object-Oriented Paradigm (12 sections)
    - Object-Oriented Paradigm:
      - year-11/object-oriented/index.md
      - Introduction to OOP: year-11/object-oriented/introduction.md
      - Classes and Objects: year-11/object-oriented/classes-objects.md
      - Attributes and Methods: year-11/object-oriented/attributes-methods.md
      - Constructors and Destructors: year-11/object-oriented/constructors.md
      - Encapsulation: year-11/object-oriented/encapsulation.md
      - Inheritance: year-11/object-oriented/inheritance.md
      - Polymorphism: year-11/object-oriented/polymorphism.md
      - Abstraction: year-11/object-oriented/abstraction.md
      - UML Class Diagrams: year-11/object-oriented/uml.md
      - Design Patterns: year-11/object-oriented/patterns.md
      - OOP Best Practices: year-11/object-oriented/best-practices.md
      - OOP Projects: year-11/object-oriented/projects.md
    
    # Module 3: Programming Mechatronics (12 sections)
    - Programming Mechatronics:
      - year-11/mechatronics/index.md
      - Introduction to Mechatronics: year-11/mechatronics/introduction.md
      - Hardware Components: year-11/mechatronics/hardware.md
      - Sensors and Inputs: year-11/mechatronics/sensors.md
      - Actuators and Outputs: year-11/mechatronics/actuators.md
      - Digital vs Analog Signals: year-11/mechatronics/signals.md
      - Microcontrollers: year-11/mechatronics/microcontrollers.md
      - GPIO Programming: year-11/mechatronics/gpio.md
      - PWM and Control: year-11/mechatronics/pwm.md
      - Communication Protocols: year-11/mechatronics/protocols.md
      - System Integration: year-11/mechatronics/integration.md
      - Real-World Applications: year-11/mechatronics/applications.md
      - Mechatronics Projects: year-11/mechatronics/projects.md
  
  # ===== YEAR 12 CONTENT =====
  
  - Year 12:
    - year-12/index.md
    
    # Module 1: Programming for the Web (13 sections)
    - Programming for the Web:
      - year-12/web-development/index.md
      - Web Fundamentals: year-12/web-development/fundamentals.md
      - HTTP and HTTPS: year-12/web-development/http.md
      - HTML Structure: year-12/web-development/html.md
      - CSS Styling: year-12/web-development/css.md
      - JavaScript Basics: year-12/web-development/javascript.md
      - DOM Manipulation: year-12/web-development/dom.md
      - Client-Server Architecture: year-12/web-development/client-server.md
      - Backend Development: year-12/web-development/backend.md
      - Databases and SQL: year-12/web-development/databases.md
      - RESTful APIs: year-12/web-development/rest-apis.md
      - Progressive Web Apps: year-12/web-development/pwa.md
      - Web Deployment: year-12/web-development/deployment.md
      - Web Projects: year-12/web-development/projects.md
    
    # Module 2: Secure Software Architecture (16 sections)
    - Secure Software Architecture:
      - year-12/security/index.md
      - Introduction to Security: year-12/security/introduction.md
      - CIA Triad: year-12/security/cia-triad.md
      - Threat Modeling: year-12/security/threat-modeling.md
      - Common Vulnerabilities: year-12/security/vulnerabilities.md
      - OWASP Top 10: year-12/security/owasp.md
      - SQL Injection: year-12/security/sql-injection.md
      - Cross-Site Scripting: year-12/security/xss.md
      - Input Validation: year-12/security/input-validation.md
      - Authentication: year-12/security/authentication.md
      - Authorization: year-12/security/authorization.md
      - Cryptography Basics: year-12/security/cryptography.md
      - Hashing and Salting: year-12/security/hashing.md
      - Secure Coding Practices: year-12/security/secure-coding.md
      - Security Testing: year-12/security/testing.md
      - Compliance and Standards: year-12/security/compliance.md
      - Security Projects: year-12/security/projects.md
    
    # Module 3: Software Automation (9 sections)
    - Software Automation:
      - year-12/automation/index.md
      - Introduction to Automation: year-12/automation/introduction.md
      - Machine Learning Basics: year-12/automation/ml-basics.md
      - Data Preprocessing: year-12/automation/preprocessing.md
      - Supervised Learning: year-12/automation/supervised.md
      - Unsupervised Learning: year-12/automation/unsupervised.md
      - Neural Networks: year-12/automation/neural-networks.md
      - AI Ethics: year-12/automation/ethics.md
      - Impact Assessment: year-12/automation/impact.md
      - Automation Projects: year-12/automation/projects.md
    
    # Module 4: Software Engineering Project (13 sections)
    - Software Engineering Project:
      - year-12/project/index.md
      - Project Overview: year-12/project/overview.md
      - Agile Methodology: year-12/project/agile.md
      - Waterfall Methodology: year-12/project/waterfall.md
      - Project Planning: year-12/project/planning.md
      - Requirements Analysis: year-12/project/requirements.md
      - System Design: year-12/project/design.md
      - Implementation: year-12/project/implementation.md
      - Testing Strategies: year-12/project/testing.md
      - Documentation: year-12/project/documentation.md
      - Version Control: year-12/project/version-control.md
      - Project Management Tools: year-12/project/tools.md
      - Project Presentation: year-12/project/presentation.md
      - Sample Projects: year-12/project/samples.md
  
  # ===== ADDITIONAL RESOURCES =====
  
  - Resources:
    - resources/index.md
    - Glossary: resources/glossary.md
    - Python Cheat Sheet: resources/python-cheatsheet.md
    - HSC Exam Tips: resources/exam-tips.md
    - Practice Quizzes: resources/quizzes.md
    - External Resources: resources/external-links.md
    - Code Examples: resources/code-examples.md
  
  - About:
    - about/index.md
    - About This Textbook: about/about.md
    - Contributing: about/contributing.md
    - License: about/license.md
    - Acknowledgments: about/acknowledgments.md
    - Changelog: about/changelog.md
