# Site Information
site_name: Software Engineering HSC Textbook
site_url: https://your-site-url.com
site_author: Your Name
site_description: Comprehensive digital textbook for NSW HSC Software Engineering

# Repository
repo_name: haleema-khatun/Software-Engineering-HSC-Textbook
repo_url: https://github.com/haleema-khatun/Software-Engineering-HSC-Textbook
edit_uri: edit/main/docs/

# Theme Configuration
theme:
  name: material
  
  # Color Palette
  palette:
    # Light mode
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  
  # Navigation Features
  features:
    - navigation.instant        # Instant loading
    - navigation.instant.progress # Loading progress bar
    - navigation.tracking       # URL updates with scroll
    - navigation.tabs           # Top-level sections as tabs
    - navigation.tabs.sticky    # Sticky navigation tabs
    - navigation.sections       # Render sections in sidebar
    - navigation.expand         # Expand all sections by default
    - navigation.path           # Show breadcrumb path
    - navigation.indexes        # Section index pages
    - navigation.top            # Back to top button
    - navigation.footer         # CRITICAL: Enables prev/next buttons in footer
    - toc.follow               # TOC follows scroll
    - toc.integrate            # Integrate TOC into navigation
    - search.suggest           # Search suggestions
    - search.highlight         # Highlight search terms
    - search.share             # Share search results
    - content.code.copy        # Copy button for code blocks
    - content.code.annotate    # Code annotations
    - content.tabs.link        # Link content tabs
    
  # Custom Styling
  font:
    text: Roboto
    code: Roboto Mono
  
  icon:
    logo: material/book-open-page-variant
    repo: fontawesome/brands/github
    
  # Favicon
  favicon: assets/favicon.png

# Plugins
plugins:
  - search:
      lang: en
      separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'
  - minify:
      minify_html: true
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago

# Extensions
markdown_extensions:
  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
      toc_depth: 3
  
  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Extra CSS and JavaScript
extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# Social Links
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/haleema-khatun/Software-Engineering-HSC-Textbook
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/yourhandle
  
  # Analytics (optional)
  # analytics:
  #   provider: google
  #   property: G-XXXXXXXXXX

# Copyright
copyright: Copyright &copy; 2024 - Licensed under MIT License

# Navigation Structure
# CRITICAL: This defines the order of pages and enables prev/next navigation
nav:
  - Home: index.md
  
  - Programming Fundamentals:
    - programming-fundamentals/index.md
    - Introduction: programming-fundamentals/introduction.md
    - Software Development Life Cycles: programming-fundamentals/sdlc.md
    - Algorithms: programming-fundamentals/algorithms.md
    - Data Structures: programming-fundamentals/data-structures.md
    - Python Basics: programming-fundamentals/python-basics.md
    - Control Structures: programming-fundamentals/control-structures.md
    - Functions: programming-fundamentals/functions.md
    - File Handling: programming-fundamentals/file-handling.md
    - Practice Exercises: programming-fundamentals/exercises.md
  
  - Object-Oriented Paradigm:
    - object-oriented/index.md
    - OOP Concepts: object-oriented/concepts.md
    - Classes and Objects: object-oriented/classes-objects.md
    - Inheritance: object-oriented/inheritance.md
    - Polymorphism: object-oriented/polymorphism.md
    - Encapsulation: object-oriented/encapsulation.md
    - Design Patterns: object-oriented/design-patterns.md
    - UML Diagrams: object-oriented/uml.md
    - Practice Projects: object-oriented/projects.md
  
  - Programming Mechatronics:
    - mechatronics/index.md
    - Introduction to Mechatronics: mechatronics/introduction.md
    - Hardware Integration: mechatronics/hardware.md
    - Sensors and Actuators: mechatronics/sensors-actuators.md
    - Embedded Systems: mechatronics/embedded-systems.md
    - Microcontrollers: mechatronics/microcontrollers.md
    - Python for Hardware: mechatronics/python-hardware.md
    - Real-world Applications: mechatronics/applications.md
  
  - Programming for the Web:
    - web-development/index.md
    - Web Fundamentals: web-development/fundamentals.md
    - HTML & CSS: web-development/html-css.md
    - JavaScript Basics: web-development/javascript.md
    - Frontend Frameworks: web-development/frontend.md
    - Backend Development: web-development/backend.md
    - Database Integration: web-development/databases.md
    - RESTful APIs: web-development/rest-apis.md
    - Progressive Web Apps: web-development/pwa.md
    - Deployment: web-development/deployment.md
  
  - Secure Software Architecture:
    - security/index.md
    - Security Principles: security/principles.md
    - Common Vulnerabilities: security/vulnerabilities.md
    - Cryptography Basics: security/cryptography.md
    - Authentication & Authorization: security/auth.md
    - Secure Coding Practices: security/secure-coding.md
    - Security Testing: security/testing.md
    - Compliance Standards: security/compliance.md
  
  - Software Automation:
    - automation/index.md
    - Introduction to AI/ML: automation/introduction.md
    - Machine Learning Basics: automation/ml-basics.md
    - Data Processing: automation/data-processing.md
    - Model Training: automation/training.md
    - Neural Networks: automation/neural-networks.md
    - Ethical Considerations: automation/ethics.md
    - Impact Assessment: automation/impact.md
    - Future of Automation: automation/future.md
  
  - Software Engineering Project:
    - project/index.md
    - Project Planning: project/planning.md
    - Requirements Analysis: project/requirements.md
    - Design Documentation: project/design.md
    - Implementation: project/implementation.md
    - Testing Strategies: project/testing.md
    - Project Management: project/management.md
    - Agile Methodologies: project/agile.md
    - Documentation: project/documentation.md
    - Project Presentation: project/presentation.md
  
  - Resources:
    - resources/index.md
    - Glossary: resources/glossary.md
    - Cheat Sheets: resources/cheatsheets.md
    - External Links: resources/links.md
    - Practice Quizzes: resources/quizzes.md
  
  - About:
    - about/index.md
    - Contributing: about/contributing.md
    - License: about/license.md
    - Changelog: about/changelog.md
