name: Bug report
description: Report a broken page, failing quiz, or code editor issue
title: "[BUG] <short title>"
labels: ["bug"]
assignees:
  - Eatham532
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug. Please provide as much detail as you can.

  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: A clear, concise description of the problem.
      placeholder: What went wrong?
    validations:
      required: true

  - type: textarea
    id: location
    attributes:
      label: Location
      description: Where did you see the issue? Include one or more of Page URL, repo file path, or Chapter/Section (e.g., 3.4).
      placeholder: |
        Page URL:
        Chapter/Section:

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: What were the exact steps?
      placeholder: |
        1. …
        2. …
        3. …
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected result
      placeholder: What did you expect to see?

  - type: textarea
    id: actual
    attributes:
      label: Actual result
      placeholder: What actually happened? Include any error text shown in the UI.

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output (optional)
      description: Paste relevant browser console output or other logs. This will be formatted as text.
      render: text

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots / recordings (optional)
      description: Add images or screen captures if helpful.

  - type: dropdown
    id: os
    attributes:
      label: Operating system
      description: Select the OS where you saw the issue.
      multiple: false
      options:
        - Windows
        - macOS
        - Linux
        - iOS
        - Android
        - iPadOS
        - ChromeOS
        - Other
    validations:
      required: true

  - type: dropdown
    id: browser
    attributes:
      label: Browser
      description: Select the browser used.
      multiple: false
      options:
        - Chrome
        - Microsoft Edge
        - Firefox
        - Safari
        - Other
    validations:
      required: true

  - type: dropdown
    id: device
    attributes:
      label: Device
      description: Select the device type.
      multiple: false
      options:
        - Desktop
        - Laptop
        - Tablet
        - Phone
        - Other
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: What part of the textbook does this relate to?
      multiple: true
      options:
        - Docs content
        - Quiz
        - Diagram rendering
        - Code editor / runner
        - Navigation / search
        - Other

  - type: textarea
    id: context
    attributes:
      label: Additional context (optional)
      description: Anything else we should know (network constraints, proxies, school devices, etc.).

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I searched existing issues and didn’t find a duplicate
        - label: I’ve provided steps to reproduce or a minimal example
        - label: I’ve removed sensitive data from logs/screenshots
