name: Content issue
description: Report typos, inaccuracies, pedagogy mismatches, accessibility, or formatting issues
title: "[CONTENT] <short title>"
labels: ["documentation"]
assignees:
  - Eatham532
body:
  - type: markdown
    attributes:
      value: |
        Help us improve the textbook! Keep it simple; just the essentials are fine.

  - type: textarea
    id: location
    attributes:
      label: Location
      description: Where is the issue? Include one or more of Page URL, repo file path, or Chapter/Section.
      placeholder: |
        Page URL:
        Chapter/Section:
    validations:
      required: true

  - type: checkboxes
    id: type-of-issue
    attributes:
      label: Type of issue
      options:
        - label: Typo/grammar
        - label: Factual accuracy
        - label: Pedagogy/sequence (teaches too early/late)
        - label: Accessibility (alt text, contrast, keyboard nav)
        - label: Formatting/layout
        - label: Broken link / reference

  - type: textarea
    id: description
    attributes:
      label: Description
      description: What’s the problem? Include the sentence/paragraph if helpful.
    validations:
      required: true

  - type: textarea
    id: proposed-fix
    attributes:
      label: Proposed fix (optional)
      description: Suggest a correction or improved wording.

  - type: input
    id: syllabus
    attributes:
      label: Syllabus mapping (optional)
      placeholder: Some reference
      description: Add a reference to a relevant syllabus dotpoint if applicable.

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots / references (optional)
      description: Add images, links to sources, or standards references.

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I searched existing issues and didn’t find a duplicate
        - label: I provided enough context to locate and fix the issue
