name: Feature request
description: Propose a new feature, improvement, or automation task
title: "[FEAT] <short title>"
labels: ["enhancement"]
assignees:
  - Eatham532
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting an improvement! We appreciate your input. Please provide as much detail as you can.

  - type: input
    id: summary
    attributes:
      label: Summary
      description: One sentence overview of the feature or improvement.
      placeholder: Short summary
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem / motivation
      description: What problem does this solve?
    validations:
      required: true

  - type: textarea
    id: proposed
    attributes:
      label: Proposed solution
      description: What should be built or changed? Any design notes or constraints?
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Primary component (optional)
      description: Pick the single best fit. You can also tick multiple areas below.
      multiple: false
      options:
        - Docs content
        - Quiz
        - Diagrams
        - Code editor / runner
        - Navigation / search
        - Other

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I searched existing feature requests and didn’t find a duplicate