# Glossary Configuration
#
# Define terms for the site-wide glossary system.
# Terms are automatically linked throughout the site with interactive tooltips.
#
# Required fields: name, definition, category
# Optional fields: aliases (list), full_form (for acronyms)

[[term]]
name = "Algorithm"
definition = "A finite sequence of well-defined instructions to solve a problem or perform a computation."
category = "Programming Fundamentals"
aliases = ["algorithms", "algorithmic"]

[[term]]
name = "API"
definition = "A set of protocols and tools for building software applications, defining how components interact."
category = "Web Development"
aliases = ["APIs", "api"]
full_form = "Application Programming Interface"

[[term]]
name = "Encapsulation"
definition = "The bundling of data and methods that operate on that data within a single unit or class, restricting direct access."
category = "OOP"
aliases = ["encapsulate", "encapsulated"]

[[term]]
name = "Inheritance"
definition = "A mechanism where a new class derives properties and behaviors from an existing class."
category = "OOP"
aliases = ["inherit", "inherits", "inherited"]

[[term]]
name = "Method"
definition = "A function defined within a class that describes the behaviors of objects created from that class."
category = "OOP"
aliases = ["methods"]

[[term]]
name = "Polymorphism"
definition = "The ability of different classes to be treated as instances of the same class through inheritance, allowing methods to behave differently based on the object."
category = "OOP"
aliases = ["polymorphic"]

[[term]]
name = "SDLC"
definition = "A structured process for planning, creating, testing, and deploying software systems."
category = "Project Management"
aliases = ["software development life cycle"]
full_form = "Software Development Life Cycle"

[[term]]
name = "Variable"
definition = "A named storage location in memory that holds a value which can change during program execution."
category = "Programming Fundamentals"
aliases = ["variables"]
